### ISSUE TITLE
[2023-07-18] Intro to Database Systems 1강 - Relational Model & Relational Algebra

### ISSUE THREAD

**Issue by CoodingPenguin** [team-mabub/robust-cs-study#1]
## 📌 개요

- `시간`: 2023-07-18(화) 21:00
- `자료`: [1강 Relational Model & Relational Algebra](https://youtu.be/uikbtpVZS2s)
- `참여자`: 펭귄, 그루트, 렉사, 나강

## ✍️ 준비

아래 양식을 복사해 스터디 준비를 완료해주세요!

```markdown
## 💬 생각

<!--강의를 듣고 생각한 내용을 3줄 내로 간단히 정리해주세요!-->

- ...

## ❓ 질문

<!--공부하면서 궁금한 점을 작성해주세요!-->

- ...

## 📚 참고 자료

<!--공부하면서 같이 공부한 자료를 첨부 및 공유해주세요!-->

- [...](...)
```

**Comment by CoodingPenguin** [comment]
## 💬 생각



- 강의자 분의 말이 생각 이상으로 빠르다. ~~(강의 편집할 때 2배속으로 했을 수도..?)~~
- DBMS가 나온 계기와 Relational Model이 무엇인지 배울 수 있었다.
- 전공 공부할 때나 개발할 때나 드는 생각이 "추상화"라는 개념이 정말 중요한 것 같다.
  - 데이터와 데이터를 저장하는 방법은 독립적이다.

## ❓ 질문



- 강의에서 INTERECTION과 JOIN 연산 결과가 똑같은 이유가 JOIN 연산 시 중복된 속성이 지워져서 그런 걸로 이해했는데, 맞는가? 
  - INTERECTION과 JOIN 연산의 차이는 JOIN은 스키마가 동일하지 않아도 된다이다.
- $\sigma_{b\textunderscore id = 102}(R \bowtie S)$ vs $(R \bowtie (\sigma_{b\textunderscore id = 102}(S))$ 중 어떤 게 더 좋다는거지?
  - 결론은 전자가 더 낫다. ~~(생각해보니 subquery 쓴거 있었는데 바꿔야 겠다..)~~ 

## 📚 참고 자료



- [Read a paper: A relational model of data for large shared data banks - Vivek Haldar | YouTube](https://youtu.be/hrbJZDKN5Rg)
- [MySQL where in (서브쿼리) vs 조인 조회 성능 비교 (5.5 vs 5.6) | 기억보단 기록을](https://jojoldu.tistory.com/520)

**Comment by jonyejin** [comment]
## 💬 생각

- 미국 강의라서 힙하다..DJ도 나오고 ex-wife얘기도 나오고 수업인데 중간에 광고도 나오고 너무 충격적이다 ㅎㅎㅎ
- 말이 빨라서 자막 없이는 보기 힘들다(본인도 빠르다고 하는거 보면 배속 아닌것같음)
- 블록체인 광기 학생은 좀 웃겼음
- 기존에는 어떠한 자료구조를 쓰냐에 따라서 구현이 많이 바뀌어서 개발자들의 수고가 많이 필요했다. tree, graph, queue..등
- Relational Model의 의의는 개발자는 간단한 자료구조(relation)으로 데이터베이스를 정의하면, DBMS의 구현이 물리적인 부분은 담당한다는 것이다.
- 그동안은 relational database를 '표'라고 생각했는데 순서가 없는 relation을 담고 있다고 생각하는게 좋을듯. 

## ❓ 질문

- 다들 어느정도로 DB를 써봤는지 궁금합니다! (저는 데베설 수업을 듣고 Postgres로 데이터 수집용DB를 써봤어요)
- intersection이랑 join의 차이는?! join은 키만 같아도 되고 intersection은 kv둘다 같아야하나?
- 어떤 식의 구현이 성능적으로 우월한가요? select->intersection, intersection->select ? 

## 📚 참고 자료

- 과제 링크(같이 해봐요): https://www.gradescope.com/courses/425272
- Course ID: PXWVR5

**Comment by Nagunt** [comment]
## 💬 생각
- 영어로 된 강의라 자막 켜고 봤는데 1강은 자막이 안 나오는 경우도 있고 듣기 힘든 경우도 있어서 좀 난감했다. 이후로도 강의자 말이 좀 빨라서 한국어로 강의 듣는 만큼 재깍재깍 이해되진 않는듯.
- 영상에서 나오는 gradescope인가? 이거 하면서 SQL 깔아서 실습도 해보면 좋을듯? 그런데 영상 보니까 이후로도 일반 SQL-92? 인가도 쓰고 MYSQL도 쓰고 SQL 종류가 하나가 아니던데 뭘로 하는게 좋을까?
- 강의자가 블록체인에 한두번 당한게 아닌듯. "블록체인은 비트코인에만 쓰는겁니다"

## ❓ 질문
- 여러가지 요소들 중에 Select Projection Syntax Intersection 등은 잘 이해했는데 Product랑 Join은 무슨 역할을 하고 뭔 차이가 있는지 모르겠다. 분명 결과값에 차이는 있었는데... (교수 캠화면 때문에 ppt 짤린 부분도 있고...)
  - 질문 잘못 적은듯. Product가 아니라 Intersection 과 Join의 차이점에 대한 의문점이었는데, 위에서 해결됨

**Comment by IamGroooooot** [comment]
## 💬 생각

- 첫 수업이라 개론적인 얘기만해서 음질이 별로였지만 이해하는데 문제는 없었다
- Ted Codd는 위대하다
- 은행에서도 레거시 DB가 많다고 들었다

## 📚 참고 자료

- gradescope을 가입할 때 대학교를 CMU로 해야 한다. 여기서 과제를 제출해볼 수 있다.
