### ISSUE TITLE
[2023-07-18] Intro to Database Systems 2강 - Modern SQL

### ISSUE THREAD

**Issue by CoodingPenguin** [team-mabub/robust-cs-study#2]
## 📌 개요

- `시간`: 2023-07-18(화) 21:00
- `자료`: [2강 Modern SQL](https://youtu.be/II5qNuxfSoo)
- `참여자`: 펭귄, 그루트, 렉사, 나강

## ✍️ 준비

아래 양식을 복사해 스터디 준비를 완료해주세요!

```markdown
## 💬 생각

<!--강의를 듣고 생각한 내용을 3줄 내로 간단히 정리해주세요!-->

- ...

## ❓ 질문

<!--공부하면서 궁금한 점을 작성해주세요!-->

- ...

## 📚 참고 자료

<!--공부하면서 같이 공부한 자료를 첨부 및 공유해주세요!-->

- [...](...)
```

**Comment by CoodingPenguin** [comment]
## 💬 생각



- 줌강 중간에 마이크 켜져서 소리 나오는 건 한국이나 해외나 똑같군..
- 대부분 알고 있긴 했는데, CTE가 신기했다. 실무에서 사용하는 사례를 한 번 찾아보면 좋을 것 같다.
- 강의에서 교수님이 PostgreSQL, MySQL, SQLite, MSSQL 4가지를 사용해서 쿼리를 보여줬는데, 너무 다 다르다. ~~이 정도면 다 통일해줘..~~
  - 실무에서는 MySQL을 쓰고 있고, 간혹 SQLite를 테스트용 DB로 쓰고 있는데 일단은 MySQL 기준으로 계속 봐야할 것 같다. 
  - 집에 [Real MySQL 책](https://product.kyobobook.co.kr/detail/S000001766482)이 있는데, 이 스터디 끝나고 이어서 해도 좋을 것 같다. 
- 드디어 [숙제](https://15445.courses.cs.cmu.edu/fall2022/homework1/)가 나왔는데, 똑같이 우리도 숙제 해오면 좋을 것 같음.

## ❓ 질문



- `WHERE`와 `HAVING`의 차이는?
  - `WHERE`는 `FROM` 바로 뒤에 오고, 모든 필드를 조건에 둘 수 있다.
  - `HAVING`은  `GROUP BY` 바로 뒤에 오고, 집계 결과에 조건을 둘 수 있다.
  - [[Oracle] SQL SELECT 쿼리 실행 순서 처리 과정 | 마이자몽](https://myjamong.tistory.com/172)
  - [GROUP BY vs. PARTITION BY: 유사점과 차이점 | 0ngoingjoy](https://kimsyoung.tistory.com/entry/GROUP-BY-vs-PARTITION-BY-%EC%9C%A0%EC%82%AC%EC%A0%90%EA%B3%BC-%EC%B0%A8%EC%9D%B4%EC%A0%90)
- `ORDER BY 1`에서 봤을 때, 컬럼 순서는 1부터 시작인가? (혹시 0은 아니겠지?)
  - 1부터 시작이다. 
- `ROW_NUMBER()`와 `RANK()`의 차이는 `ROW_NUMBER()`는 "1개, 2개, ..." 이렇게 세는 것이고 `RANK()`는 "1등, 공동 2등, 4등, ..." 이런 차이가 맞는가?
  - 맞다. 
- `OVER()` 안에 들어갈 수 있는 건 뭐가 있을까? `OVER()` 안에서 정확히 어떻게 그룹화하는지가 궁금하다.
  -  [SELECT - OVER 절(Transact-SQL) | Microsoft Learn](https://learn.microsoft.com/ko-kr/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver15)
  - `PARTITION BY` / `ORDER BY` / `ROWS/RANGE` 그리고 윈도우 함수가 가능하다고 한다.
  - 추가적으로 더 궁금해진 게 테이블에 `ORDER BY`랑 다른게 뭔가 하니 기본적으로 동일한데 `OVER` 안에서 쓰는 건 윈도우 범위 내에서 하기 떄문에 좀 더 성능 향상이 있다고 한다.

## 📚 참고 자료



- [where와 having의 차이 | 완숙의 에그머니🍳](https://wansook0316.github.io/cs/database/2020/04/25/where-having-%EC%B0%A8%EC%9D%B4.html)
- [[SQL] Order by 1에 대하여 | Sherry IT Blog](https://javagirl.tistory.com/11)
- [SELECT - OVER 절(Transact-SQL) | Microsoft Learn](https://learn.microsoft.com/ko-kr/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver15)
- [What Is a Common Table Expression (CTE) in SQL? | LearnSQL](https://learnsql.com/blog/what-is-common-table-expression/)

**Comment by Nagunt** [comment]
## 💬 생각

- SQL에서 사용하는 기본적인 쿼리문들 쭉 훑어본듯.
- string 관련해서 불평 많이 하던데 역시 string은 만악의 근원이다.

## ❓ 질문

- CTE를 임시로 결과값을 저장해두는 공간으로 이해했는데 맞는지 모르겠다.
  - OS의 클립보드 등과 같이, 쿼리문에 따른 결과값을 임시로 저장해 두고 사용할 수 있는 공간이 맞다.
- RANK() 랑 ROW_NUMBER()을 영상에서 학생이 질문했을 때 RANK는 Order Position을 가져오고 
ROW_NUMBER는 row position을 가져온다는데 둘이 차이가 있는건지? ORDER BY에 따라서 달라질 수 있는건가?
  - 중복값의 존재 유무 (공동 순위 등), ORDER BY 에 따른 차이가 발생할 수 있는 점이 다르다.
- GROUP BY? ORDER BY랑 PARTITION BY가 있던데 둘이 뭔 차이가 있는걸까?
  - GROUP BY와 PARTITION BY의 차이점은 GROUP BY는 결과값을 새로운 테이블에 생성하지만 PARTITION BY는 기존 테이블과 같이 볼 수 있다. 자세한 것은 다음 링크 참조. 
  - [GROUP BY vs. PARTITION BY: 유사점과 차이점 | Ongoingjoy](https://kimsyoung.tistory.com/entry/GROUP-BY-vs-PARTITION-BY-%EC%9C%A0%EC%82%AC%EC%A0%90%EA%B3%BC-%EC%B0%A8%EC%9D%B4%EC%A0%90)

**Comment by jonyejin** [comment]
## 💬 생각

- 항상 SQL을 짜는 과정이 머리에서 생각하는 순서와 다르다고 생각해서 어려웠다. 차라리 pandas가 훨씬 쉽다고 느꼈는데, 강의를 들으면서 생각해 보니까 최대한 최적화를 하려고 해서 그랬던 것 같다. 교수님의 말씀대로라면 내부 구현에 대해서는 생각하지 않고 직관적으로만 짜면 되는듯?(그래도 내부 구현이 너무 궁금하다…)
- nested query < Common Table Expression < View 순으로 자주 쓰는것 같은데 좋은 습관일까?

## ❓ 질문

- 그러면 having은 group by 뒤에 계산되므로 더 연산량이 높은건 아니라는거겠지?
- 교수님 터미널 설정 어떤건지 아시는분? (단축키로 db 바꿔가면서 테스트 하는것 같은데..)

## 📒 메모
- **“EXPLAIN”을 붙이면 dbms의 plan을 알려준다.**
- output redirection하려면 INSERT INTO TABLENAME (SELECT * );


## 🥹스터디 하면서 배운거/공부할거 TODO

- autoincrement와 where로 구현해야함(offset, limit 노노!)
    - 찾아봐야겠다….
- CTE..turing complete…?
   - CTE와 view의 차이…?

**Comment by IamGroooooot** [comment]
## 💬 생각

- CTE를 통해 turing complete해지는 것은 처음 알았다
- OFFSET과 LIMIT에 관해서 조심해야 된다는 부분이 공감 됐다
- DB에 따라 다른 부분이 많기 때문에 결국 개발자도 Explain을 뜨면서 내 쿼리가 어떻게 도는지 확인해야 된다고 생각이 들었다

## ❓ 질문

- 과제해보실 분?
  - 과제는 5, 6강 듣고 할지 말지 결정
- 여러 종류의 서브쿼리에 장/단점이 궁금
  - 스칼라
    - 스칼라 서브쿼리는 성능이 좋지도 않고 웬만하면 조인으로도 다 표현이 가능하다고 함
    - 꼭 필요 한 경우만 쓰는 것 추천함
  - 인라인뷰
    - 서브쿼리가 하나의 테이블처럼 사용되는 경우
  - 상호연관 등

## 📚 참고 자료
- 서브 쿼리는 Order by 못했던 듯
